const expectedProfile = {
    resultCode: '20000',
    resultDescription: 'Success',
    developerMessage: 'Success',
    data: {
      resultCode: '20000',
      resultDescription: 'Success',
      developerMessage: 'Request successful',
      resultData: {
        subScriptionProfile: {
          caId: '3238258979',
          emailLanguage: 'tha',
          ivrLanguage: 'tha',
          msisdn: '66659330882',
          publicType: 'msisdn',
          smsLanguage: 'tha',
          subscriptionState: 'Active',
          subscriptionStateDate: '15/05/2023 00:00:00',
          ussdLanguage: 'tha',
          dataChargingSystem: 'CBS',
          baId: '',
          saId: '',
          billingSystemAccountId: '20166659330882N5FBUo',
          billingSystemCustomerId: '10166659330882N5FBUo',
          chargeType: 'Pre-paid',
          segment: 'Classic',
          registerDate: '15/05/2023 00:00:00',
          brandId: '5',
          servicePackageId: '8',
          classOfService: '160355',
          luckyLists: [
            {
              luckyName: '',
              luckyType: '',
            },
          ],
          networkType: '03',
          subNetworkType: 'Pre-paid',
          churnScore: '',
          churnScoreReason: '',
          paGroup: '',
          paGroupEffectiveDate: '',
          regionCode: 'C3',
          cosId: '',
          segmentEffectiveDate: '15/05/2023 00:00:00',
          segmentExpiryDate: '31/03/2033 00:00:00',
          clvSegment: '',
          remark: '',
          assetId: '',
          amendment: '',
          brandName: '',
          suspendType: '',
          suspendCount: '',
          suspendFraudCount: '',
          firstSuspendCountDate: '',
          blacklistStatus: '',
          installmentFlag: '',
          contractPhoneFlag: '',
          contractFlag: '',
          billingMainProductId: '',
          simSerialNo: '1730001808822',
          authorizePersonFlag: '',
          fbbContactNo: '',
          billingSystem: 'CBS',
          ocrFlag: '',
          ocrReflag: '',
          ocrReason: '',
          ocrApproveBy: '',
          ocrApproveDate: '',
          ocrDate: '',
          ocrErrorCode: '',
          ocrLastUpdate: '',
          ocrLastUpdateBy: '',
          statusReason: '',
          idenFaceFlag: '',
          businessRegId: '',
          regLocationCode: '2002',
          productType: '3PP',
          classifyCode: 'Normal',
          mobileNoStatus: 'R',
          mobileNoStatusDate: '15/05/2023 00:00:00',
          moiFlag: 'N',
          moiDate: '',
          businessGrp: '',
          updateLocation: '2002',
          binNo: '',
          focMember: '',
          maxMsg: '',
          applyMobileNo: '',
          applyLocation: '2002',
          msgLanguage: '',
          regUserId: 'nikhom49',
          cleaningFlag: 'N',
          cleaningDate: '',
          smartCase: '',
          cardVersion: '',
          ocrReflagApprove: '',
          smartCardFlag: 'N',
          balance: '0',
          validity: '1',
          applyLocationName: '',
          serviceYear: {
            year: '0',
            month: '0',
            day: '29',
          },
          channel: 'My Channel',
          applyDate: '15/05/2023 00:00:00',
          amendmentReason: 'Default by Siebel',
          mobileType: 'Volume-Based',
          reason: 'PI',
          effectiveServicePI: '15/05/2023 00:00:00',
          cbsMigrateDate: '',
          cbsMigrateFlag: 'N',
          insMigrateDate: '',
          insMigrateFlag: 'N',
          vpnFlag: '',
          vpnEffectiveDate: '',
          vpnExpireDate: '',
          loanFlag: 'N',
          piFlag: 'Y',
          firstActivateDate: '15/05/2023 00:00:00',
          reasonCode: '',
          simStatus: 'Active',
          serviceDay: '29',
          nType: 'CPE',
          reconnectDate: '',
          fbbContactNo2: '',
          fbbContactNo3: '',
          maxSpeedUL: '',
          maxSpeedDL: '',
          suspendDate: '',
          suspendReason: '',
          credCreditAmount: {
            creditAmount: '0',
            usageAmount: '0',
            remainAmount: '0',
          },
          changeBillingSystemDate: '',
          familyAuth: '',
          cimAssetRemark: '',
          counterMain: '',
          counterOntop: '',
          maxCounterMain: '',
          maxCounterOntop: '',
          ds3notificationPolicyControl: '',
          ds3customerCategory: 'residential',
          productName: '3G',
          instanceName: 'AWN',
        },
        nafaProfile: {},
      },
      networkTypeMapping: {
        ntypeId: '23',
        ntype: 'CBS',
        mobileLocation: 'Non BOS',
        description: 'Prepaid3G Non Bos',
        businessType: 'Prepaid',
        networkType: '3G',
        customerType: 'Residential',
        mobileType: 'eService',
      },
    },
  };
  
  const expectedAccount = {
    resultCode: '20000',
    resultDescription: 'Success',
    developerMessage: 'Success',
    data: {
      resultCode: '20000',
      resultDescription: 'Success',
      developerMessage: 'Request successful',
      resultData: {
        subscriptionAccount: {
          msisdn: '66659330882',
          subscriptionState: 'Active',
          subscriptionStateDate: '15/05/2023 00:00:00',
          customerAccount: [
            {
              accountState: 'Active',
              accountStateDate: '15/05/2023 00:00:00',
              accountSegment: '',
              accountCategory: 'R',
              accountSubCategory: '',
              accountGroupCode: '',
              accountGroupName: '',
              accountSpecialGroup: '',
              title: 'นาย',
              customerName: 'สำหรับซัพพอร์ต ทีมอื่น',
              idCardNo: '1102700613934',
              idCardType: 'ID_CARD',
              birthday: '08/10/1996 00:00:00',
              email: '',
              address: [
                {
                  engFlag: '',
                  houseNo: '8',
                  moo: '-',
                  mooban: 'คอนโด',
                  building: 'อาคารP',
                  floor: '37',
                  room: '69',
                  soi: 'ลาดพร้าว101',
                  street: '-',
                  amphur: 'วังทองหลาง',
                  tumbol: 'คลองเจ้าคุณสิงห์',
                  province: 'กรุงเทพ',
                  zipCode: '10310',
                },
              ],
              caId: '3238258979',
              nationality: '',
              billCycle: '',
              blacklistStatus: '',
              serviceLevel: '',
              gender: 'M',
              cardIssueDate: '',
              cardExpired: '',
              hobby: [],
              titleEng: '',
              customerNameEng: 'Support Mobile',
              serviceSubtype: 'PI',
              titleCode: '2',
              creditLimit: '',
              idCardTypeDesc: 'บัตรประชาชน',
              idCardTypeNo: '1',
              urlPicture:
                '/export/home/MNT_NFS/PrepaidIden_Image/2019082810/201908281037100099_0656041209_EE1080359_pic.jpg',
              rsmeFlag: '',
              caRegisterDate: '15/05/2023 00:00:00',
            },
          ],
          billingAccount: [],
          serviceAccount: [],
          subscriptionHolder: [
            {
              birthday: '08/10/1996 00:00:00',
              contactClass: '',
              province: 'กรุงเทพ',
              title: 'นาย',
              contactName: 'สำหรับซัพพอร์ต ทีมอื่น',
              contactFirstname: 'สำหรับซัพพอร์ต',
              contactLastname: 'ทีมอื่น',
              idCardType: 'ID_CARD',
              idCardNo: '1102700613934',
              privateCode: '',
              privateCodeFlag: '',
              socialMedia: [],
              nationality: '',
              localLanguage: '',
              urlPicture:
                '/export/home/MNT_NFS/PrepaidIden_Image/2019082810/201908281037100099_0656041209_EE1080359_pic.jpg',
              urlDate: '',
              contactId: '',
              contactPhone: [],
            },
          ],
        },
        nafaProfile: {},
      },
    },
  };
  
  
  export { expectedAccount, expectedProfile};